name: android-ci
on:
  push:
    branches: [*]
  pull_request:
    branches: [*]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test script
        run: echo Hello, world!