name: android-ci
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build debug
        run: ./gradlew assembleDebug
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: androidApp-debug.apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk