name: android-ci
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Clean
        run: ./gradlew clean

      - name: Build
        run: ./gradlew :androidApp:assembleDebug

      - name: Upload artifact to build info
        uses: actions/upload-artifact@v3.1.0
        with:
          name: androidApp-debug.apk
          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk

  distribute:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: androidApp-debug.apk

      - name: Get latest commit
        id: vars
        run: echo ::set-output name=LATEST_COMMIT_MESSAGE::${github.event.commits[0].message}

      - name: Upload artifact to FAD
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: androidApp-debug.apk
          releaseNotes: ${{ steps.vars.outputs.LATEST_COMMIT_MESSAGE }}
